### ISSUE TITLE
FYI, koop

### ISSUE THREAD

**Issue by timwis** [caseycesari/map-gather#4]
Hey Casey! Just wanted to make sure you were aware of [koop](http://koopjs.github.io/), an open source product Esri's built that has some parallels to this project. It pulls in data from a variety of providers (AGOL, Socrata, CKAN, GitHub, to name a few), puts it into a cache (such as Postgres), and serves it up as GeoJSON or a FeatureService. They've kept it pretty modular, so I'd suspect the [koop-agol](https://github.com/koopjs/koop-agol) module could be used to pull a feature service from ArcGIS Online into a database.

**Comment by caseycesari** [comment]
Thanks for the heads up, @timwis! Looks like a cool project.
